// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tb_training_logs/enums/exercises.dart';
import 'package:tb_training_logs/enums/plan_status.dart';
import 'package:tb_training_logs/enums/workout_time_status.dart';
import 'package:tb_training_logs/enums/workout_type.dart';
import 'package:tb_training_logs/models/exercise_model.dart';
import 'package:tb_training_logs/models/training_plan.dart';
import 'package:tb_training_logs/models/workout_day_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeadliftAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(LegsExercisesAdapter());
    registerAdapter(PlanStatusAdapter());
    registerAdapter(PullExercisesAdapter());
    registerAdapter(PushExercisesAdapter());
    registerAdapter(TrainingPlanAdapter());
    registerAdapter(WorkoutDayAdapter());
    registerAdapter(WorkoutExerciseAdapter());
    registerAdapter(WorkoutTimeStatusAdapter());
    registerAdapter(WorkoutTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeadliftAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(LegsExercisesAdapter());
    registerAdapter(PlanStatusAdapter());
    registerAdapter(PullExercisesAdapter());
    registerAdapter(PushExercisesAdapter());
    registerAdapter(TrainingPlanAdapter());
    registerAdapter(WorkoutDayAdapter());
    registerAdapter(WorkoutExerciseAdapter());
    registerAdapter(WorkoutTimeStatusAdapter());
    registerAdapter(WorkoutTypeAdapter());
  }
}
